name: Build and Publish package

on:
  release:
    types: [published]

jobs:
  build-and-publish-deb-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Run Releases Sync Action
        uses: https://git.0xmax42.io/actions/releases-sync@main
        with:
          gitea_token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
          gitea_url: https://git.0xmax42.io
          gitea_owner: li-praktikum
          gitea_repo: n8n-nodes-tanss-api
          tag_name: ${{ github.event.release.tag_name }}
          github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
          github_owner: 0xmax42
          github_repo: n8n-nodes-tanss-api
